version: "3.6"

services:
  postgres:
    image: postgres:10.5
    container_name: tax-postgres
    restart: unless-stopped
    networks: 
    - subnet
    ports:
      - "5432:5432"
    volumes:
      - ./etc/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  service:
    container_name: tax-service
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks: 
      - subnet
    environment:
      - GO111MODULE=on
      - TAX_SERVICE_DSN=postgres://postgres:postgres@tax-postgres:5432/tax_service?sslmode=disable

networks:
  subnet:
    external: true      