// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tax_service.proto

package tax_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeleteRateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRateResponse) Reset()         { *m = DeleteRateResponse{} }
func (m *DeleteRateResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRateResponse) ProtoMessage()    {}
func (*DeleteRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{0}
}
func (m *DeleteRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRateResponse.Unmarshal(m, b)
}
func (m *DeleteRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRateResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRateResponse.Merge(dst, src)
}
func (m *DeleteRateResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRateResponse.Size(m)
}
func (m *DeleteRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRateResponse proto.InternalMessageInfo

type GetRateRequest struct {
	// @inject_tag: json:"ip"
	IpData *GeoIdentity `protobuf:"bytes,1,opt,name=ip_data,json=ipData,proto3" json:"ip_data,omitempty"`
	// @inject_tag: json:"user"
	UserData             *GeoIdentity `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRateRequest) Reset()         { *m = GetRateRequest{} }
func (m *GetRateRequest) String() string { return proto.CompactTextString(m) }
func (*GetRateRequest) ProtoMessage()    {}
func (*GetRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{1}
}
func (m *GetRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateRequest.Unmarshal(m, b)
}
func (m *GetRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateRequest.Marshal(b, m, deterministic)
}
func (dst *GetRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateRequest.Merge(dst, src)
}
func (m *GetRateRequest) XXX_Size() int {
	return xxx_messageInfo_GetRateRequest.Size(m)
}
func (m *GetRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateRequest proto.InternalMessageInfo

func (m *GetRateRequest) GetIpData() *GeoIdentity {
	if m != nil {
		return m.IpData
	}
	return nil
}

func (m *GetRateRequest) GetUserData() *GeoIdentity {
	if m != nil {
		return m.UserData
	}
	return nil
}

type GeoIdentity struct {
	// @inject_tag: json:"zip"
	Zip string `protobuf:"bytes,1,opt,name=zip,proto3" json:"zip,omitempty"`
	// @inject_tag: json:"country"
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: json:"state,omitempty"
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoIdentity) Reset()         { *m = GeoIdentity{} }
func (m *GeoIdentity) String() string { return proto.CompactTextString(m) }
func (*GeoIdentity) ProtoMessage()    {}
func (*GeoIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{2}
}
func (m *GeoIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoIdentity.Unmarshal(m, b)
}
func (m *GeoIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoIdentity.Marshal(b, m, deterministic)
}
func (dst *GeoIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoIdentity.Merge(dst, src)
}
func (m *GeoIdentity) XXX_Size() int {
	return xxx_messageInfo_GeoIdentity.Size(m)
}
func (m *GeoIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_GeoIdentity proto.InternalMessageInfo

func (m *GeoIdentity) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *GeoIdentity) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GeoIdentity) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GeoIdentity) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type GetRateResponse struct {
	VatRate              *TaxRate `protobuf:"bytes,1,opt,name=vat_rate,json=vatRate,proto3" json:"vat_rate,omitempty"`
	IpDataPriority       bool     `protobuf:"varint,2,opt,name=ip_data_priority,json=ipDataPriority,proto3" json:"ip_data_priority,omitempty"`
	UserDataPriority     bool     `protobuf:"varint,3,opt,name=user_data_priority,json=userDataPriority,proto3" json:"user_data_priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRateResponse) Reset()         { *m = GetRateResponse{} }
func (m *GetRateResponse) String() string { return proto.CompactTextString(m) }
func (*GetRateResponse) ProtoMessage()    {}
func (*GetRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{3}
}
func (m *GetRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateResponse.Unmarshal(m, b)
}
func (m *GetRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateResponse.Marshal(b, m, deterministic)
}
func (dst *GetRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateResponse.Merge(dst, src)
}
func (m *GetRateResponse) XXX_Size() int {
	return xxx_messageInfo_GetRateResponse.Size(m)
}
func (m *GetRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateResponse proto.InternalMessageInfo

func (m *GetRateResponse) GetVatRate() *TaxRate {
	if m != nil {
		return m.VatRate
	}
	return nil
}

func (m *GetRateResponse) GetIpDataPriority() bool {
	if m != nil {
		return m.IpDataPriority
	}
	return false
}

func (m *GetRateResponse) GetUserDataPriority() bool {
	if m != nil {
		return m.UserDataPriority
	}
	return false
}

type TaxRate struct {
	// @inject_tag: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"zip"
	Zip string `protobuf:"bytes,2,opt,name=zip,proto3" json:"zip,omitempty"`
	// @inject_tag: json:"country"
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: gorm:"type:varchar(2)"
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// @inject_tag: json:"rate"
	Rate                 float32  `protobuf:"fixed32,6,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaxRate) Reset()         { *m = TaxRate{} }
func (m *TaxRate) String() string { return proto.CompactTextString(m) }
func (*TaxRate) ProtoMessage()    {}
func (*TaxRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{4}
}
func (m *TaxRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaxRate.Unmarshal(m, b)
}
func (m *TaxRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaxRate.Marshal(b, m, deterministic)
}
func (dst *TaxRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxRate.Merge(dst, src)
}
func (m *TaxRate) XXX_Size() int {
	return xxx_messageInfo_TaxRate.Size(m)
}
func (m *TaxRate) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxRate.DiscardUnknown(m)
}

var xxx_messageInfo_TaxRate proto.InternalMessageInfo

func (m *TaxRate) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaxRate) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *TaxRate) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *TaxRate) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *TaxRate) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *TaxRate) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type GetRatesRequest struct {
	// @inject_tag: json:"zip"
	Zip string `protobuf:"bytes,1,opt,name=zip,proto3" json:"zip,omitempty"`
	// @inject_tag: json:"country"
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: json:"limit,omitempty"
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// @inject_tag: json:"offset,omitempty"
	Offset               int32    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRatesRequest) Reset()         { *m = GetRatesRequest{} }
func (m *GetRatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRatesRequest) ProtoMessage()    {}
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{5}
}
func (m *GetRatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatesRequest.Unmarshal(m, b)
}
func (m *GetRatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatesRequest.Marshal(b, m, deterministic)
}
func (dst *GetRatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatesRequest.Merge(dst, src)
}
func (m *GetRatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRatesRequest.Size(m)
}
func (m *GetRatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatesRequest proto.InternalMessageInfo

func (m *GetRatesRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *GetRatesRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *GetRatesRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *GetRatesRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetRatesRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type DeleteRateRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRateRequest) Reset()         { *m = DeleteRateRequest{} }
func (m *DeleteRateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRateRequest) ProtoMessage()    {}
func (*DeleteRateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{6}
}
func (m *DeleteRateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRateRequest.Unmarshal(m, b)
}
func (m *DeleteRateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRateRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRateRequest.Merge(dst, src)
}
func (m *DeleteRateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRateRequest.Size(m)
}
func (m *DeleteRateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRateRequest proto.InternalMessageInfo

func (m *DeleteRateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRatesResponse struct {
	// @inject_tag: json:"rates"
	Rates                []*TaxRate `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetRatesResponse) Reset()         { *m = GetRatesResponse{} }
func (m *GetRatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatesResponse) ProtoMessage()    {}
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_f152d53a1036b3b7, []int{7}
}
func (m *GetRatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatesResponse.Unmarshal(m, b)
}
func (m *GetRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatesResponse.Merge(dst, src)
}
func (m *GetRatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatesResponse.Size(m)
}
func (m *GetRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatesResponse proto.InternalMessageInfo

func (m *GetRatesResponse) GetRates() []*TaxRate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteRateResponse)(nil), "tax_service.DeleteRateResponse")
	proto.RegisterType((*GetRateRequest)(nil), "tax_service.GetRateRequest")
	proto.RegisterType((*GeoIdentity)(nil), "tax_service.GeoIdentity")
	proto.RegisterType((*GetRateResponse)(nil), "tax_service.GetRateResponse")
	proto.RegisterType((*TaxRate)(nil), "tax_service.TaxRate")
	proto.RegisterType((*GetRatesRequest)(nil), "tax_service.GetRatesRequest")
	proto.RegisterType((*DeleteRateRequest)(nil), "tax_service.DeleteRateRequest")
	proto.RegisterType((*GetRatesResponse)(nil), "tax_service.GetRatesResponse")
}

func init() { proto.RegisterFile("tax_service.proto", fileDescriptor_tax_service_f152d53a1036b3b7) }

var fileDescriptor_tax_service_f152d53a1036b3b7 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x38, 0x4e, 0x26, 0xc2, 0xa4, 0xa3, 0x08, 0x59, 0xe1, 0x2b, 0x5a, 0x2e, 0x11,
	0x42, 0x45, 0x14, 0x71, 0xed, 0x01, 0x2a, 0xaa, 0x9c, 0x40, 0xdb, 0x72, 0x8e, 0x96, 0x78, 0x2b,
	0xad, 0x54, 0x62, 0xb3, 0x3b, 0x89, 0x92, 0x5e, 0x38, 0xf0, 0x2f, 0xf8, 0x1d, 0xfc, 0x40, 0xb4,
	0xbb, 0x76, 0xe2, 0x16, 0x47, 0x5c, 0xb8, 0xed, 0xcc, 0xbc, 0x99, 0x7d, 0xef, 0xed, 0xd8, 0x70,
	0x4c, 0x62, 0x33, 0x37, 0x52, 0xaf, 0xd5, 0x42, 0x9e, 0x94, 0xba, 0xa0, 0x02, 0x07, 0x8d, 0x14,
	0x1b, 0x01, 0x9e, 0xcb, 0x1b, 0x49, 0x92, 0x0b, 0x92, 0x5c, 0x9a, 0xb2, 0x58, 0x1a, 0xc9, 0x6e,
	0x21, 0xbd, 0x90, 0xe4, 0x53, 0xdf, 0x57, 0xd2, 0x10, 0xbe, 0x81, 0x44, 0x95, 0xf3, 0x5c, 0x90,
	0xc8, 0x82, 0x49, 0x30, 0x1d, 0x9c, 0x66, 0x27, 0xcd, 0xc9, 0x17, 0xb2, 0x98, 0xe5, 0x72, 0x49,
	0x8a, 0xb6, 0xbc, 0xab, 0xca, 0x73, 0x41, 0x02, 0xdf, 0x41, 0x7f, 0x65, 0xa4, 0xf6, 0x4d, 0xe1,
	0x3f, 0x9a, 0x7a, 0x16, 0x6a, 0xdb, 0xd8, 0x02, 0x06, 0x8d, 0x02, 0x0e, 0x21, 0xba, 0x55, 0xa5,
	0xbb, 0xb4, 0xcf, 0xed, 0x11, 0x33, 0x48, 0x16, 0xc5, 0x6a, 0x49, 0x7a, 0xeb, 0xa6, 0xf6, 0x79,
	0x1d, 0x22, 0x42, 0x67, 0xa1, 0x68, 0x9b, 0x45, 0x2e, 0xed, 0xce, 0x38, 0x82, 0xd8, 0x90, 0x20,
	0x99, 0x75, 0x5c, 0xd2, 0x07, 0xec, 0x57, 0x00, 0x0f, 0x77, 0x0a, 0xbd, 0x68, 0x7c, 0x0d, 0xbd,
	0xb5, 0xa0, 0xb9, 0xb6, 0x60, 0xaf, 0x71, 0x74, 0x87, 0xee, 0x95, 0xd8, 0x38, 0x7c, 0xb2, 0x16,
	0xae, 0x11, 0xa7, 0x30, 0xac, 0x3c, 0x99, 0x97, 0x5a, 0x15, 0xda, 0x5e, 0x6d, 0x19, 0xf5, 0x78,
	0xea, 0x2d, 0xf8, 0x5c, 0x65, 0xf1, 0x15, 0xe0, 0xce, 0x8a, 0x3d, 0x36, 0x72, 0xd8, 0x61, 0xad,
	0xbc, 0x46, 0xb3, 0x9f, 0x01, 0x24, 0xd5, 0x65, 0x98, 0x42, 0xa8, 0x72, 0x47, 0xe7, 0x01, 0x0f,
	0x55, 0x5e, 0xdb, 0x11, 0xb6, 0xda, 0x11, 0xb5, 0xdb, 0xd1, 0x69, 0xb3, 0x23, 0x6e, 0xd8, 0x61,
	0x91, 0x4e, 0x76, 0x77, 0x12, 0x4c, 0x43, 0xee, 0xce, 0xec, 0xc7, 0xce, 0x21, 0x53, 0x2f, 0xc1,
	0x7f, 0x78, 0x8b, 0x1b, 0xf5, 0x4d, 0x91, 0x63, 0x14, 0x73, 0x1f, 0xe0, 0x23, 0xe8, 0x16, 0xd7,
	0xd7, 0x46, 0x92, 0xe3, 0x14, 0xf3, 0x2a, 0x62, 0x2f, 0xe0, 0xb8, 0xb9, 0x9a, 0x9e, 0xc2, 0x3d,
	0x3f, 0xd8, 0x19, 0x0c, 0xf7, 0x2c, 0xab, 0x87, 0x7c, 0x09, 0xb1, 0x55, 0x60, 0xb2, 0x60, 0x12,
	0x1d, 0x7c, 0x45, 0x0f, 0x39, 0xfd, 0x1d, 0x02, 0x5c, 0x89, 0xcd, 0xa5, 0xaf, 0xe2, 0x47, 0x48,
	0xaa, 0x71, 0xf8, 0xf8, 0xde, 0xae, 0x36, 0x3f, 0x87, 0xf1, 0x93, 0xf6, 0x62, 0xf5, 0xf9, 0x1c,
	0xe1, 0x0c, 0x7a, 0x35, 0x2d, 0x6c, 0xc5, 0xd6, 0x9e, 0x8e, 0x9f, 0x1e, 0xa8, 0xee, 0x46, 0x9d,
	0x41, 0xfa, 0x41, 0x4b, 0x41, 0xf2, 0x93, 0xfe, 0x52, 0xe6, 0x96, 0x59, 0xab, 0xa0, 0x71, 0x6b,
	0x96, 0x1d, 0xe1, 0x25, 0xa4, 0x7b, 0x1b, 0xdf, 0x6f, 0x67, 0x39, 0x3e, 0xbb, 0x83, 0xfc, 0xcb,
	0xe3, 0xf1, 0xf3, 0x83, 0xf5, 0x9a, 0xd4, 0xd7, 0xae, 0xfb, 0x95, 0xbc, 0xfd, 0x13, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x2e, 0xce, 0xf7, 0x5f, 0x04, 0x00, 0x00,
}
