// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tax_service.proto

package tax_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_c1ec3f5aad762695, []int{0}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type TaxEntry struct {
	// @inject_tag: json:"zip"
	ZipCode string `protobuf:"bytes,1,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	// @inject_tag: json:"country"
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: json:"state,omitempty"
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// @inject_tag: json:"rate"
	Rate                 float32  `protobuf:"fixed32,6,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaxEntry) Reset()         { *m = TaxEntry{} }
func (m *TaxEntry) String() string { return proto.CompactTextString(m) }
func (*TaxEntry) ProtoMessage()    {}
func (*TaxEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_c1ec3f5aad762695, []int{1}
}
func (m *TaxEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaxEntry.Unmarshal(m, b)
}
func (m *TaxEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaxEntry.Marshal(b, m, deterministic)
}
func (dst *TaxEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxEntry.Merge(dst, src)
}
func (m *TaxEntry) XXX_Size() int {
	return xxx_messageInfo_TaxEntry.Size(m)
}
func (m *TaxEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TaxEntry proto.InternalMessageInfo

func (m *TaxEntry) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *TaxEntry) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *TaxEntry) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *TaxEntry) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *TaxEntry) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type RateLookupQuery struct {
	// @inject_tag: json:"zip"
	ZipCode string `protobuf:"bytes,1,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	// @inject_tag: json:"country"
	Country string `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	// @inject_tag: json:"city,omitempty"
	City string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	// @inject_tag: json:"state,omitempty"
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateLookupQuery) Reset()         { *m = RateLookupQuery{} }
func (m *RateLookupQuery) String() string { return proto.CompactTextString(m) }
func (*RateLookupQuery) ProtoMessage()    {}
func (*RateLookupQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_c1ec3f5aad762695, []int{2}
}
func (m *RateLookupQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLookupQuery.Unmarshal(m, b)
}
func (m *RateLookupQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLookupQuery.Marshal(b, m, deterministic)
}
func (dst *RateLookupQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLookupQuery.Merge(dst, src)
}
func (m *RateLookupQuery) XXX_Size() int {
	return xxx_messageInfo_RateLookupQuery.Size(m)
}
func (m *RateLookupQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLookupQuery.DiscardUnknown(m)
}

var xxx_messageInfo_RateLookupQuery proto.InternalMessageInfo

func (m *RateLookupQuery) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *RateLookupQuery) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *RateLookupQuery) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *RateLookupQuery) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type GetSingleRateResponse struct {
	Rate                 *TaxEntry `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	NotAccurate          bool      `protobuf:"varint,2,opt,name=not_accurate,json=notAccurate,proto3" json:"not_accurate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetSingleRateResponse) Reset()         { *m = GetSingleRateResponse{} }
func (m *GetSingleRateResponse) String() string { return proto.CompactTextString(m) }
func (*GetSingleRateResponse) ProtoMessage()    {}
func (*GetSingleRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_c1ec3f5aad762695, []int{3}
}
func (m *GetSingleRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSingleRateResponse.Unmarshal(m, b)
}
func (m *GetSingleRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSingleRateResponse.Marshal(b, m, deterministic)
}
func (dst *GetSingleRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSingleRateResponse.Merge(dst, src)
}
func (m *GetSingleRateResponse) XXX_Size() int {
	return xxx_messageInfo_GetSingleRateResponse.Size(m)
}
func (m *GetSingleRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSingleRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSingleRateResponse proto.InternalMessageInfo

func (m *GetSingleRateResponse) GetRate() *TaxEntry {
	if m != nil {
		return m.Rate
	}
	return nil
}

func (m *GetSingleRateResponse) GetNotAccurate() bool {
	if m != nil {
		return m.NotAccurate
	}
	return false
}

type GetRatesResponse struct {
	// @inject_tag: json:"rates"
	Rates                []*TaxEntry `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRatesResponse) Reset()         { *m = GetRatesResponse{} }
func (m *GetRatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRatesResponse) ProtoMessage()    {}
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tax_service_c1ec3f5aad762695, []int{4}
}
func (m *GetRatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRatesResponse.Unmarshal(m, b)
}
func (m *GetRatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRatesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRatesResponse.Merge(dst, src)
}
func (m *GetRatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRatesResponse.Size(m)
}
func (m *GetRatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRatesResponse proto.InternalMessageInfo

func (m *GetRatesResponse) GetRates() []*TaxEntry {
	if m != nil {
		return m.Rates
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyResponse)(nil), "tax_service.EmptyResponse")
	proto.RegisterType((*TaxEntry)(nil), "tax_service.TaxEntry")
	proto.RegisterType((*RateLookupQuery)(nil), "tax_service.RateLookupQuery")
	proto.RegisterType((*GetSingleRateResponse)(nil), "tax_service.GetSingleRateResponse")
	proto.RegisterType((*GetRatesResponse)(nil), "tax_service.GetRatesResponse")
}

func init() { proto.RegisterFile("tax_service.proto", fileDescriptor_tax_service_c1ec3f5aad762695) }

var fileDescriptor_tax_service_c1ec3f5aad762695 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0xfa, 0x19, 0xa7, 0x96, 0xea, 0x60, 0x21, 0x16, 0x85, 0xba, 0xa7, 0x8a, 0xd0, 0x43,
	0xbd, 0x2b, 0xa2, 0xa5, 0x0a, 0x5e, 0x4c, 0x7a, 0x2f, 0x31, 0x1d, 0x24, 0x58, 0xb3, 0x4b, 0x32,
	0x91, 0xb6, 0xe0, 0xdf, 0xf2, 0xf7, 0xc9, 0x6e, 0x5a, 0x69, 0x4a, 0x25, 0x27, 0x6f, 0xbb, 0x6f,
	0xde, 0xbe, 0xf7, 0xf2, 0x26, 0x70, 0xcc, 0xfe, 0x62, 0x9a, 0x50, 0xfc, 0x19, 0x06, 0x34, 0x50,
	0xb1, 0x64, 0x89, 0xcd, 0x2d, 0x48, 0xb4, 0xa1, 0x35, 0xfa, 0x50, 0xbc, 0x74, 0x29, 0x51, 0x32,
	0x4a, 0x48, 0x7c, 0x81, 0x3d, 0xf1, 0x17, 0xa3, 0x88, 0xe3, 0x25, 0x9e, 0x82, 0xbd, 0x0a, 0xd5,
	0x34, 0x90, 0x33, 0x72, 0xac, 0x9e, 0xd5, 0x3f, 0x70, 0x1b, 0xab, 0x50, 0xdd, 0xcb, 0x19, 0xa1,
	0x03, 0x8d, 0x40, 0xa6, 0x9a, 0xe5, 0x94, 0xb3, 0xc9, 0xfa, 0x8a, 0x08, 0xd5, 0x20, 0xe4, 0xa5,
	0x53, 0x31, 0xb0, 0x39, 0xe3, 0x09, 0xd4, 0x12, 0xf6, 0x99, 0x9c, 0xaa, 0x01, 0xb3, 0x8b, 0x66,
	0xc6, 0x1a, 0xac, 0xf7, 0xac, 0x7e, 0xd9, 0x35, 0x67, 0xa1, 0xa0, 0xed, 0xfa, 0x4c, 0xcf, 0x52,
	0xbe, 0xa7, 0xea, 0x25, 0xa5, 0x7f, 0x4f, 0x21, 0x08, 0x3a, 0x63, 0x62, 0x2f, 0x8c, 0xde, 0xe6,
	0xa4, 0xad, 0x37, 0x4d, 0xe0, 0xe5, 0x3a, 0x9e, 0xf6, 0x6c, 0x0e, 0x3b, 0x83, 0xed, 0x26, 0x37,
	0x15, 0x65, 0xa9, 0xf1, 0x02, 0x0e, 0x23, 0xc9, 0x53, 0x3f, 0x08, 0x52, 0xf3, 0x44, 0x87, 0xb1,
	0xdd, 0x66, 0x24, 0xf9, 0x6e, 0x0d, 0x89, 0x5b, 0x38, 0x1a, 0x13, 0x6b, 0x83, 0xe4, 0xd7, 0xe1,
	0x0a, 0x6a, 0x7a, 0x96, 0x38, 0x56, 0xaf, 0xf2, 0xb7, 0x45, 0xc6, 0x19, 0x7e, 0x97, 0x01, 0x26,
	0xfe, 0xc2, 0xcb, 0xc6, 0x78, 0x03, 0x0d, 0x2f, 0xd3, 0xc3, 0xfd, 0xef, 0xba, 0xdd, 0x1c, 0x9c,
	0xdf, 0x72, 0x09, 0x1f, 0x01, 0x1e, 0x68, 0x4e, 0x6c, 0xbe, 0x19, 0xcf, 0x72, 0xdc, 0x9d, 0x0d,
	0x14, 0x28, 0x79, 0xd0, 0xca, 0x15, 0x58, 0x20, 0x26, 0x72, 0xd3, 0xbd, 0xd5, 0x8b, 0x12, 0x3e,
	0x81, 0xbd, 0xa9, 0xab, 0x40, 0xef, 0x7c, 0x57, 0x2f, 0xd7, 0xb1, 0x28, 0xbd, 0xd6, 0xcd, 0x6f,
	0x7f, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x33, 0xfc, 0xf7, 0x26, 0x0b, 0x03, 0x00, 0x00,
}
